CONTENT_MODERATOR_ENDPOINT=$(az cognitiveservices account show -g $RESOURCE_GROUP_NAME -n $CONTENT_MODERATOR_NAME --query "properties.endpoint" -o tsv)
CONTENT_MODERATOR_KEY=$(az cognitiveservices account keys list -g $RESOURCE_GROUP_NAME -n $CONTENT_MODERATOR_NAME --query "key1" -o tsv)

echo "CONTENT_MODERATOR_ENDPOINT: $CONTENT_MODERATOR_ENDPOINT"
echo "CONTENT_MODERATOR_KEY: ${CONTENT_MODERATOR_KEY:0:4}..."

export CONTENT_MODERATOR_ENDPOINT=$CONTENT_MODERATOR_ENDPOINT
export CONTENT_MODERATOR_KEY=$CONTENT_MODERATOR_KEY
