CONTENT_SAFETY_ENDPOINT=$(az cognitiveservices account show -g $RESOURCE_GROUP_NAME -n $CONTENT_SAFETY_NAME --query "properties.endpoint" -o tsv)
CONTENT_SAFETY_KEY=$(az cognitiveservices account keys list -g $RESOURCE_GROUP_NAME -n $CONTENT_SAFETY_NAME --query "key1" -o tsv)

echo "CONTENT_SAFETY_ENDPOINT: $CONTENT_SAFETY_ENDPOINT"
echo "CONTENT_SAFETY_KEY: ${CONTENT_SAFETY_KEY:0:4}..."

export CONTENT_SAFETY_ENDPOINT=$CONTENT_SAFETY_ENDPOINT
export CONTENT_SAFETY_KEY=$CONTENT_SAFETY_KEY
